# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca3ddb0c0b45ad1b6db5b06c9b10cbb763eb7f57d1736ed5a9d9f6d802126550de888f938892eb658efb269c0614392b15702f781c306a3bfa71a54500ac0477

test:
  secret_key_base: db5a55d195f1d5819f8ab00367f0668c856370870af631f78d176d6fd682288ae7307fd3d6c4ffa6d52dd4e559c955bc7dbb882d11875bbf238e0919147d03c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
